export const team = [
  {
    name: 'Oleh Popovych',
    speciality: 'FullStack | Team Lead',
    image: 'https://media.mate.academy/fit-in/512x512/users/243426/avatars/current-1690489032351.jpg',
    telegram: 'https://t.me/olehpopovych0',
    gitHub: 'https://github.com/OlegPopovych',
    LinkedIn: 'https://www.linkedin.com/in/oleh-popovych-a23152246/',
    email: 'popovycholeh0@gmail.com',
  },
  {
    name: 'Oksana Drozdyk',
    speciality: 'FullStack',
    image: 'https://media.mate.academy/fit-in/512x512/users/99580/avatars/current-1696708687508.jpg',
    telegram: 'https://t.me/o_drozzdyk',
    gitHub: 'https://github.com/o-drozzdyk',
    LinkedIn: '-',
    email: 'oksana.drozdyk.dev@gmail.com',
  },
  {
    name: 'Vladyslav Atanov',
    speciality: 'FullStack',
    image: 'https://media.mate.academy/fit-in/512x512/users/365983/avatars/current-1694717830831.jpg',
    telegram: 'https://t.me/Sintax1ss',
    gitHub: 'https://github.com/sintax1s',
    LinkedIn: 'https://www.linkedin.com/in/vladyslav-atanov-9931a02a4/',
    email: 'atanov.vladyslav@gmail.com',
  },
  {
    name: 'Tetyana Poletayeva',
    speciality: 'FullStack',
    image: 'https://media.mate.academy/fit-in/512x512/users/162697/avatars/current-1694694863568.jpg',
    telegram: 'https://t.me/TetyanPol',
    gitHub: 'https://github.com/tetyana-pol',
    LinkedIn: 'https://www.linkedin.com/in/tetiana-poletaieva-09b45b144/',
    email: 'ptupob@gmail.com',
  },
  {
    name: 'Hryhorii Starykov',
    speciality: 'FullStack',
    image: 'https://media.mate.academy/fit-in/512x512/users/157696/avatars/current-1690581758045.png',
    telegram: 'https://t.me/starykovhryhorii',
    gitHub: 'https://github.com/hrysta',
    LinkedIn: '-',
    email: 'hr.starykov@gmail.com',
  },
  {
    name: 'Maksym Semeniuk',
    speciality: 'FullStack',
    image: 'https://media.mate.academy/fit-in/512x512/users/383902/avatars/current-1689165702893.jpg',
    telegram: 'https://t.me/xovisage',
    gitHub: 'https://github.com/MVoutch',
    LinkedIn: 'https://www.linkedin.com/in/maxim-semenuik-dev/',
    email: 'xovisage@gmail.com',
  },
  {
    name: 'Ivanna Zaiets',
    speciality: 'FullStack',
    image: 'https://media.mate.academy/fit-in/512x512/users/380766/avatars/current-1696410459276.jpg',
    telegram: 'https://t.me/swugre',
    gitHub: 'https://github.com/ivaZaiets',
    LinkedIn: 'https://www.linkedin.com/in/ivanna-zaiets-6122532a0/',
    email: 'iva.zaiets.dev@gmail.com',
  },
];
