export const colors = [
  { name: 'black', hash: '#000000' },
  { name: 'green', hash: '#a0cba4' },
  { name: 'purple', hash: '#CBC3E3' },
  { name: 'red', hash: '#ff0000' },
  { name: 'white', hash: '#ffffff' },
  { name: 'yellow', hash: '#ffff00' },
  { name: 'gold', hash: '#F6E0C9' },
  { name: 'silver', hash: '#e2e4e1' },
  { name: 'spacegray', hash: '#808080' },
  { name: 'midnightgreen', hash: '#092E20' },
  { name: 'rosegold', hash: '#E0BFB8' },
  { name: 'rose-gold', hash: '#E0BFB8' },
  { name: 'coral', hash: '#ff7f50' },
  { name: 'spaceblack' , hash: '#333334'},
  { name: 'graphite' , hash: '#414141'},
  { name: 'sierrablue' , hash: '#69abce'},
  { name: 'midnight' , hash: '#011635'},
  { name: 'blue' , hash: '#51A0D5'},
  { name: 'pink' , hash: '#b76e79'},
  { name: 'starlight', hash: '#f0f0dc'},
  { name: 'skyblue', hash: '#87CEEB'},
  { name: 'sky-blue', hash: '#87CEEB'},
];
